Update prod-api_app-fitnesschatbot-prod-001.yml

diff --git a/.github/workflows/prod-api_app-fitnesschatbot-prod-001.yml b/.github/workflows/prod-api_app-fitnesschatbot-prod-001.yml
--- a/.github/workflows/prod-api_app-fitnesschatbot-prod-001.yml
+++ b/.github/workflows/prod-api_app-fitnesschatbot-prod-001.yml
@@ -35,10 +35,14 @@ jobs:
         
       - name: Patch chromadb to use pysqlite3
         run: |
-          FILE=$(find venv -path "*chromadb/__init__.py" | head -n 1)
-          echo "__import__('pysqlite3')" | cat - "$FILE" > temp && mv temp "$FILE"
-          echo "import sys" >> "$FILE"
-          echo "sys.modules['sqlite3'] = sys.modules.pop('pysqlite3')" >> "$FILE"
+          set -e
+          FILE=$(find venv -type f -path "*chromadb/__init__.py" | head -n 1)
+          if [ -z "$FILE" ]; then
+            echo "chromadb/__init__.py not found in virtual environment."
+            exit 1
+          fi
+          sed -i '1i__import__("pysqlite3")\nimport sys\nsys.modules["sqlite3"] = sys.modules.pop("pysqlite3")' "$FILE"
+
 
       - name: Zip artifact for deployment
         run: zip release.zip ./* -r
@@ -76,5 +80,6 @@ jobs:
           slot-name: 'Production'
 
           publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C1D5852005ED4E77A3A5EC023DB4FDCE }}
+
 
 
